[package]
name = "anthelia"
version = "0.1.0"
edition = "2021"
authors = ["Patchethium"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"serde-pickle" = "1.1"
serde = "1.0"
anyhow = "1.0.75"
ordered-float = "4.1.1"